---
- name: Create required dirs
  loop:
    - /etc/mongodb
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - arbiter

- name: Create init dirs
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.file:
    path: "/etc/mongodb/{{ item.name }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - arbiter

- name: Write init script
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart arbiter
  ansible.builtin.template:
    src: init.j2
    dest: "/etc/mongodb/{{ item.name }}/init.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - arbiter

- name: Write keyfile content
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart arbiter
  ansible.builtin.copy:
    content: "{{ item.keyfile }}"
    dest: "/etc/mongodb/{{ item.name }}.key"
    owner: "{{ item.owner | default('999') }}"
    group: "{{ item.group | default('root') }}"
    mode: u=rw,g=,o=
  tags:
    - arbiter

- name: Write service file
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart arbiter
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/arbiter-{{ item.name }}.service"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - arbiter

- name: Pull docker image
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - true if item.pull is not defined else item.pull
  community.docker.docker_image:
    name: "mongo:{{ item.version }}"
    source: pull
  tags:
    - arbiter

- name: Start arbiter service
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.systemd:
    name: "arbiter-{{ item.name }}"
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - arbiter

...
