# Standards: 0.1
---
- name: Restart arbiter
  loop: "{{ arbiter_instances }}"
  loop_control:
    label: "{{ item.name }}"
  systemd:
    name: "arbiter-{{ item.name }}"
    state: restarted
    daemon_reload: True

...
